PytestDeprecationWarning for pytest.collect.X
Adopts `_pytest.deprecated.PYTEST_COLLECT_MODULE` from f1d51ba1f.

The main difference to pytest is that `import pytest.collect` did not
work since ae234786e (3.0.7-161, 2017 - no issues reported for it),
and this is behavior is kept here for backward compatibility.

With ae234786e (3.0.7-161):

> ModuleNotFoundError: No module named 'pytest.collect'; 'pytest' is not a package

The error changed in e5bd7fb05 (5.3.1-12):

> ModuleNotFoundError: No module named 'pytest.collect'